# Generated by Django 4.2.23 on 2025-08-07 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='characters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('set', models.TextField()),
                ('main_stat', models.TextField()),
                ('stat_1', models.IntegerField()),
                ('stat_2', models.IntegerField()),
                ('stat_3', models.IntegerField()),
                ('stat_4', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_drive', to='character.character')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_drive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
